const products = [
  {
    id: 1,
    name: "HONDA WR-V",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint repellendus odio laborum doloremque temporibus asperiores quisquam provident! Deleniti voluptas sit iure omnis sed doloremque a iusto, vel cupiditate incidunt architecto.",
    price: "700",
    img: "https://h-h-auto.de/wp-content/uploads/2019/12/2F4O2Fk2.jpg",
    features: {
      bodyStyle: "Convertible",
      door: "2",
      engine: "3.4L Mid-Engine V6",
      fuelType: "Gasoline",
      fuelMileage: "20 City / 28 Hwy",
      condition: "Brand New",
      waeeanty: "3 Years Limited",
    },
  },
  {
    id: 2,
    name: "HONDA WR-V",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint repellendus odio laborum doloremque temporibus asperiores quisquam provident! Deleniti voluptas sit iure omnis sed doloremque a iusto, vel cupiditate incidunt architecto.",
    price: "700",
    img: "https://h-h-auto.de/wp-content/uploads/2019/12/2F4O2Fk2.jpg",
    features: {
      bodyStyle: "Convertible",
      door: "2",
      engine: "3.4L Mid-Engine V6",
      fuelType: "Gasoline",
      fuelMileage: "20 City / 28 Hwy",
      condition: "Brand New",
      waeeanty: "3 Years Limited",
    },
  },
  {
    id: 3,
    name: "HONDA WR-V",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint repellendus odio laborum doloremque temporibus asperiores quisquam provident! Deleniti voluptas sit iure omnis sed doloremque a iusto, vel cupiditate incidunt architecto.",
    price: "700",
    img: "https://h-h-auto.de/wp-content/uploads/2019/12/2F4O2Fk2.jpg",
    features: {
      bodyStyle: "Convertible",
      door: "2",
      engine: "3.4L Mid-Engine V6",
      fuelType: "Gasoline",
      fuelMileage: "20 City / 28 Hwy",
      condition: "Brand New",
      waeeanty: "3 Years Limited",
    },
  },
  {
    id: 4,
    name: "HONDA WR-V",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint repellendus odio laborum doloremque temporibus asperiores quisquam provident! Deleniti voluptas sit iure omnis sed doloremque a iusto, vel cupiditate incidunt architecto.",
    price: "700",
    img: "https://h-h-auto.de/wp-content/uploads/2019/12/2F4O2Fk2.jpg",
    features: {
      bodyStyle: "Convertible",
      door: "2",
      engine: "3.4L Mid-Engine V6",
      fuelType: "Gasoline",
      fuelMileage: "20 City / 28 Hwy",
      condition: "Brand New",
      waeeanty: "3 Years Limited",
    },
  },
  {
    id: 5,
    name: "HONDA WR-V",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint repellendus odio laborum doloremque temporibus asperiores quisquam provident! Deleniti voluptas sit iure omnis sed doloremque a iusto, vel cupiditate incidunt architecto.",
    price: "700",
    img: "https://h-h-auto.de/wp-content/uploads/2019/12/2F4O2Fk2.jpg",
    features: {
      bodyStyle: "Convertible",
      door: "2",
      engine: "3.4L Mid-Engine V6",
      fuelType: "Gasoline",
      fuelMileage: "20 City / 28 Hwy",
      condition: "Brand New",
      waeeanty: "3 Years Limited",
    },
  },
  {
    id: 6,
    name: "HONDA WR-V",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint repellendus odio laborum doloremque temporibus asperiores quisquam provident! Deleniti voluptas sit iure omnis sed doloremque a iusto, vel cupiditate incidunt architecto.",
    price: "700",
    img: "https://h-h-auto.de/wp-content/uploads/2019/12/2F4O2Fk2.jpg",
    features: {
      bodyStyle: "Convertible",
      door: "2",
      engine: "3.4L Mid-Engine V6",
      fuelType: "Gasoline",
      fuelMileage: "20 City / 28 Hwy",
      condition: "Brand New",
      waeeanty: "3 Years Limited",
    },
  },
  {
    id: 7,
    name: "HONDA WR-V",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint repellendus odio laborum doloremque temporibus asperiores quisquam provident! Deleniti voluptas sit iure omnis sed doloremque a iusto, vel cupiditate incidunt architecto.",
    price: "700",
    img: "https://h-h-auto.de/wp-content/uploads/2019/12/2F4O2Fk2.jpg",
    features: {
      bodyStyle: "Convertible",
      door: "2",
      engine: "3.4L Mid-Engine V6",
      fuelType: "Gasoline",
      fuelMileage: "20 City / 28 Hwy",
      condition: "Brand New",
      waeeanty: "3 Years Limited",
    },
  },
  {
    id: 8,
    name: "HONDA WR-V",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint repellendus odio laborum doloremque temporibus asperiores quisquam provident! Deleniti voluptas sit iure omnis sed doloremque a iusto, vel cupiditate incidunt architecto.",
    price: "700",
    img: "https://h-h-auto.de/wp-content/uploads/2019/12/2F4O2Fk2.jpg",
    features: {
      bodyStyle: "Convertible",
      door: "2",
      engine: "3.4L Mid-Engine V6",
      fuelType: "Gasoline",
      fuelMileage: "20 City / 28 Hwy",
      condition: "Brand New",
      waeeanty: "3 Years Limited",
    },
  },
  {
    id: 9,
    name: "HONDA WR-V",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint repellendus odio laborum doloremque temporibus asperiores quisquam provident! Deleniti voluptas sit iure omnis sed doloremque a iusto, vel cupiditate incidunt architecto.",
    price: "700",
    img: "https://h-h-auto.de/wp-content/uploads/2019/12/2F4O2Fk2.jpg",
    features: {
      bodyStyle: "Convertible",
      door: "2",
      engine: "3.4L Mid-Engine V6",
      fuelType: "Gasoline",
      fuelMileage: "20 City / 28 Hwy",
      condition: "Brand New",
      waeeanty: "3 Years Limited",
    },
  },
  {
    id: 10,
    name: "HONDA WR-V",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint repellendus odio laborum doloremque temporibus asperiores quisquam provident! Deleniti voluptas sit iure omnis sed doloremque a iusto, vel cupiditate incidunt architecto.",
    price: "700",
    img: "https://h-h-auto.de/wp-content/uploads/2019/12/2F4O2Fk2.jpg",
    features: {
      bodyStyle: "Convertible",
      door: "2",
      engine: "3.4L Mid-Engine V6",
      fuelType: "Gasoline",
      fuelMileage: "20 City / 28 Hwy",
      condition: "Brand New",
      waeeanty: "3 Years Limited",
    },
  },
];
